#!/usr/bin/python3

def raise_exception():
    print("new" + 3454)
